### ISSUE TITLE
Transparency lost on png images

### ISSUE THREAD

**Issue by tri613** [alextanhongpin/compress.js#3]
Hi,

Thanks for this awesome library, it's very handy and simple.
However, if I try to compress a png image with transparency, 
the transparent parts would turn into black as result.

Is there anyway to solve this?

Thanks for all the good works again!

P.S. This is what looks like on the demo page, the original image is [here](https://g.twimg.com/about/feature-corporate/image/twitterbird_RGB.png).
![08_x_08_17-05-43](https://user-images.githubusercontent.com/10163715/26920836-cfd629c0-4c6c-11e7-9636-f50da0df0fc1.png)

**Comment by alextanhongpin** [comment]
Unfortunately, I couldn't manage to work it out. It's a known issue as `PNG` is already a compressed data format. Therefore, the code I wrote will convert the images to `JPEG` in order to perform compression, which results in the loss of transparency. I'll probably add a note at the README so that others know about this issue.

**Comment by tri613** [comment]
I see. Thanks!
